# mysql innodb cluster
mysql-innodbcluster:
  enabled: true
  # mysql credentials
  credentials:
    root:
      user: root
      password: root
      host: "%"

  # mysql tls config
  tls:
    useSelfSigned: true

  # mysql server config
  serverInstances: 1
  baseServerId: 1000
  datadirVolumeClaimTemplate:
    storageClassName: aws-ebs
    resources:
      requests:
        storage: 20Gi

  # mysql router config
  router:
    instances: 1

  # mysql logs config
  logs:
    error:
      verbosity: 3
      collect: false
    slowQuery:
      enabled: true
      longQueryTime: 1

  # mysql metrics config
  metrics:
    enable: true
    image: prom/mysqld-exporter:v0.13.0
    monitor: true
    monitorSpec: {}

  # mysql mycnf config
  mycnf: ""

  # mysql pod spec config
  podSpec:
    containers:
      - name: mysql
        resources:
          requests:
            memory: "2Gi"
            cpu: "2000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: com.yesglasses.pod
                    operator: NotIn
                    values:
                      - mysql
              topologyKey: kubernetes.io/hostname

# mysql operator config
mysql-operator:
  enabled: true
  envs:
    k8sClusterDomain: cluster.local

# phpmyadmin config
phpmyadmin:
  enabled: true
  hostname: pma.local
  mysql:
    hosts: mysql-cluster
    ports: 3306
