production_mode: staging

app:
  example:
    basicAuth:
      enabled: true
    containers:
      nginx:
        hostnames:
          - test.bufio.cn
        monitor:
          enabled: true
        logger:
          enabled: true
      
      php:
        monitor:
          enabled: true
        logger:
          enabled: true
    
    hpa: true

mysql:
  enabled: true
  credentials:
    root:
      password: "yesglasses!"

  serverInstances: 1
  routerInstances: 1
  backupIndex: 0
  cloneIndex: 0
  storage: 20Gi

volumes:
  - name: sites
    storage: 20Gi
    storageClassName: aws-efs
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /sites
      type: Directory
    mode: static

  - name: log
    storage: 20Gi
    storageClassName: aws-s3
    accessModes:
      - ReadWriteOnce
    mode: dynamic

  - name: mysql-backup
    storage: 20Gi
    storageClassName: aws-s3
    accessModes:
      - ReadWriteOnce
    mode: dynamic

cron:
  mysqlBackup:
    enabled: true

routes: {}

kube-prometheus-stack:
  enabled: true
  alertmanager:
    enabled: true
    config:
      global:
        resolve_timeout: 5m
        smtp_from: "system@yesglasses.com"
        smtp_smarthost: "email-smtp.us-west-2.amazonaws.com:587"
        smtp_auth_username: "AKIAYJN44QGEYLHKPJHG"
        smtp_auth_password: "BJ6MpvfuHvgIFbK3lRYFM9fwiBNbbSGfJYPo4Px/KEtX"
        smtp_require_tls: true
      inhibit_rules: []
      route:
        group_by: ['namespace']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'null'
        routes:
        - receiver: 'null'
          matchers:
            - alertname = "Watchdog"

      receivers:
      - name: 'null'
      - name: 'yehua'
        email_configs:
        - to: "799475742@qq.com"
          send_resolved: true

      templates:
      - '/etc/alertmanager/config/*.tmpl'

cadvisor:
  enabled: true

fluentd:
  enabled: true

prometheus-adapter:
  enabled: true