production_mode: local

app:
  php:
    example:
      hostnames:
        - "*.yes.io"
      basicAuth:
        enabled: false
        username: "yes"
        password: "glasses!!"
      serverSnippet:
      replicas: 2
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      image: registry.bufio.cn/php:latest
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: default
      resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      scriptFile: /sites/$subdomain/index.php
      mounts:
        - mountPath: /sites/
          name: sites
      listen: 9000
      health:
      monitor:
        enabled: false
        scrapeUri: tcp://127.0.0.1:9001/fpm_status
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 20m
            memory: 32Mi

      restartPolicy: Always
      volumes:
        - name: sites
          persistentVolumeClaim:
              claimName: sites

dockerRegistry:
  secrets:
    default:
      server: registry.bufio.cn
      email: admin@bufio.cn
      username: admin
      password: admin


# mysql innodb cluster
mysql:
  enabled: true
  name: mysql-cluster
  rootSecretName: mysql-secret
  version: 8.4.1
  credentials:
    root:
      user: root
      password: root
      host: "%"

  serverInstances: 1
  routerInstances: 1
  backupIndex: 1
  cloneIndex: 1
  storage: 10Gi

  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 4096Mi

  monitor:
    enabled: true

cron:
  mysqlBackup:
    enabled: false

mysql-operator:
  envs:
    k8sClusterDomain: cluster.local