production_mode: local

app:
  php:
    example:
      hostnames:
        - "*.yes.local"
      basicAuth:
        enabled: false
        username: "yes"
        password: "glasses!!"
      serverSnippet: |
        if ($host ~ ^(?<subdomain>[^.]+).yes.local$) {
            set $subdomain $subdomain;
        }
      replicas: 1
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      image: php:8.3-fpm
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      scriptFile: /sites/www.yesglasses.com/$subdomain/index.php
      mounts:
        - mountPath: /sites/
          name: sites
      bodyLimit: 32M
      monitor:
        enabled: false
        scrapeUri: tcp://127.0.0.1:9001/fpm_status
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 20m
            memory: 32Mi

      restartPolicy: Always
      volumes:
        - name: sites
          persistentVolumeClaim:
            claimName: sites-provider

dockerRegistry:
  secrets:
    default:
      server: registry.bufio.cn
      email: admin@bufio.cn
      username: admin
      password: admin
