production_mode: local

app:
  php:
    example:
      hostnames:
        - "*.yes.io"
      basicAuth:
        enabled: false
        username: "yes"
        password: "glasses!!"
      serverSnippet:
      replicas: 2
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      image: php:latest
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
      resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      scriptFile: /sites/$subdomain/index.php
      mounts:
        - mountPath: /sites/
          name: sites
      listen: 9000
      monitor:
        enabled: false
        scrapeUri: tcp://127.0.0.1:9001/fpm_status
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 20m
            memory: 32Mi

      restartPolicy: Always
      volumes:
        - name: sites
          persistentVolumeClaim:
              claimName: sites

dockerRegistry:
  secrets:
    default:
      server: registry.bufio.cn
      email: admin@bufio.cn
      username: admin
      password: admin