production_mode: local

app:
  php:
    example:
      hostnames:
        - "www.bufio.cn"
      basicAuth:
        enabled: true
        username: "yes"
        password: "glasses!!"
      serverSnippet:
      replicas: 1
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      image: registry.bufio.cn/php:latest
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: default
      resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      scriptFile: /sites/index.php
      mounts:
      listen: 9000
      health:
      monitor:
        enabled: false
        scrapeUri: tcp://127.0.0.1:9001/fpm_status
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 20m
            memory: 32Mi

      restartPolicy: Always
      volumes:

dockerRegistry:
  secrets:
    default:
      server: registry.bufio.cn
      email: admin@bufio.cn
      username: admin
      password: admin

gitRegistry:


# mysql innodb cluster
mysql:
  enabled: false
  name: mysql-cluster
  rootSecretName: mysql-secret
  version: 8.4.1
  credentials:
    root:
      user: root
      password: root
      host: "%"

  serverInstances: 3
  routerInstances: 2
  backupIndex: 2
  cloneIndex: 2
  storage: 20Gi

  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 2000m
      memory: 4096Mi

  monitor:
    enabled: true

volumes:
  # - name: sites
  #   storage: 10Gi
  #   storageClassName: aws-efs
  #   accessModes:
  #     - ReadWriteOnce
  #   hostPath:
  #     path: /sites
  #     type: Directory
  #   mode: static

cron:
  mysqlBackup:
    enabled: false

mysql-operator:
  envs:
    k8sClusterDomain: cluster.local

phpmyadmin:
  fullnameOverride: phpmyadmin