
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: jenkins-update-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch", "update"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: jenkins-update-roler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: jenkins-update-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-update-role
subjects:
- kind: ServiceAccount
  name: jenkins-update-roler
  namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-update-roler-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: jenkins-update-roler
type: kubernetes.io/service-account-token