{{ $namespace := .Release.Namespace }}
{{- if hasKey .Values "routes" }}
{{- range $name, $route := .Values.routes }}
{{- if $route.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  parentRefs:
  - name: {{ $namespace }}-gateway
  hostnames:
  {{- range $_, $hostname := $route.hostnames }}
  - {{ $hostname }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ $route.backend.host }}
      port: {{ $route.backend.port }}

---
{{- end }}
{{- end }}
{{- end }}