{{ $namespace := .Release.Namespace }}
{{- if not (empty .Values.volumes) }}
{{- range $_, $volume := .Values.volumes }}
{{- if eq (default "dynamic" $volume.mode) "static" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ $volume.name }}
spec:
  capacity:
    storage: {{ default "20Gi" $volume.storage }}
  accessModes:
    {{ toYaml $volume.accessModes | nindent 4 }}
  storageClassName: {{ $volume.storageClassName }}
  volumeMode: Filesystem
  {{- if not (empty $volume.csi) }}
  csi:
    {{ toYaml $volume.csi | nindent 4 }}
  {{- end }}
  {{- if not (empty $volume.hostPath) }}
  hostPath:
    {{ toYaml $volume.hostPath | nindent 4 }}
  {{- end }}
  {{- if not (empty $volume.mountOptions) }}
  mountOptions:
    {{ toYaml $volume.mountOptions | nindent 4 }}
  {{- end }}
{{- end }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    com.yesglasses.pvc: {{ $volume.name }}
  name: {{ $volume.name }}
  namespace: {{ $namespace }}
spec:
  accessModes:
    {{ toYaml $volume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ default "20Gi" $volume.storage }}
  storageClassName: {{ $volume.storageClassName }}
  volumeMode: Filesystem
  {{- if eq $volume.mode "static" }}
  volumeName: pv-{{ $volume.name }}
  {{- end }}

---
{{- end }}
{{- end }}