apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: {{ .Release.Namespace }}
  labels:
    com.yesglasses.pvc: gitea-data
spec:
  storageClassName: {{ .Values.git.storageClassName }}
  accessModes:
    - {{ .Values.git.accessMode }}
  resources:
    requests:
      storage: {{ .Values.git.capacity }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: {{ .Release.Namespace }}
  labels:
    com.yesglasses.deployment: gitea
spec:
  selector:
    matchLabels:
      com.yesglasses.pod: gitea
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        com.yesglasses.pod: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.22.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 3000
              name: tcp-web
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
          volumeMounts:
            - name: gitea-data
              mountPath: /data
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: {{ .Release.Namespace }}
  labels:
    com.yesglasses.service: gitea
spec:
  selector:
    com.yesglasses.pod: gitea
  ports:
    - port: 3000
      targetPort: 3000
      name: tcp-web

{{- if .Values.git.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: git
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 32M
spec:
  rules:
    - host: {{ .Values.git.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: gitea
                port:
                  number: 3000
{{- end }}