# log-collector config
enabled: true

# fluent-bit config
config: |
  [SERVICE]
    Flush             1
    Daemon            Off
    Log_Level         info
    Parsers_File      /fluent-bit/etc/fluent-bit-parse.conf

  [INPUT]
    Name              tail
    Tag               kube.*
    Path              /var/log/containers/*.log
    DB                /var/log/flb_kube.db
    DB.sync           Normal
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Refresh_Interval  10
    Parser            docker 

  [FILTER]
    Name                kubernetes 
    Match               kube.*
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Labels              false
    Annotations         false
    Kube_Tag_Prefix     kube.var.log.containers.

  [Filter]
    Name          nest
    Match         kube.*
    Operation     lift
    Nested_under  kubernetes
    Add_prefix    kubernetes_

  [Filter]
    Name      modify
    Match     kube.*
    Remove    stream
    Remove    kubernetes_pod_id
    Remove    kubernetes_host
    Remove    kubernetes_container_hash
    Remove    kubernetes_docker_id
    Remove    kubernetes_container_image
    Remove    kubernetes_pod_ip
    Remove    time

  [OUTPUT]
    Name                es
    Match               kube.*
    Host                elasticsearch-master
    Port                9200
    Logstash_Format     On
    Suppress_Type_Name   On

# fluent-bit parses config
parseConfig: |
  [PARSER]
    Name         docker
    Format       json
    Time_Key     time
    Time_Format  %Y-%m-%dT%H:%M:%S.%L
    Time_Keep    On　
