apiVersion: v2
name: yesglasses
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  # local elasticsearch
  - name: elasticsearch
    repository: "file://charts/elasticsearch"
    version: 0.1.0
    condition: elasticsearch.enabled

  # local ingress nginx gateway
  - name: ingress
    repository: "file://charts/ingress"
    version: 0.1.0

  # local log collector
  - name: log-collector
    repository: "file://charts/log-collector"
    version: 0.1.0
    condition: log-collector.enabled

  # local mysql cluster
  - name: mysql
    repository: "file://charts/mysql"
    version: 0.1.0
    condition: mysql.enabled

  # local prometheus
  - name: prometheus
    repository: "file://charts/prometheus"
    version: 0.1.0
    condition: prometheus.enabled

  # local repository
  - name: repository
    repository: "file://charts/repository"
    version: 0.1.0
    condition: repository.enabled

  # local sites provider
  - name: sites-provider
    repository: "file://charts/sites-provider"
    version: 0.1.0
    condition: sites-provider.enabled

  # local storageclass
  - name: storageclass
    repository: "file://charts/storageclass"
    version: 0.1.0
    condition: storageclass.enabled
