
# mysql innodb cluster
mysql:
  enabled: true
  name: mysql-cluster
  rootSecretName: mysql-secret
  version: 8.4.3
  credentials:
    root:
      user: root
      password: root
      host: "%"

  serverInstances: 1
  routerInstances: 1
  backupIndex: 1
  cloneIndex: 1
  storage: 10Gi

  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 4096Mi

  monitor:
    enabled: true

cron:
  mysqlBackup:
    enabled: false

mysql-operator:
  envs:
    k8sClusterDomain: cluster.local